# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 02:09
from __future__ import unicode_literals

import cdrive_fcp.utils.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account_source',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(default='avatars/default-img.jpg', upload_to=cdrive_fcp.utils.utils.PathUtils.get_avatar_file_name),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='on_screen_name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
