# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='games',
            field=models.ManyToManyField(to='game.Game'),
        ),
    ]
