# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accumulated_spending',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
    ]
