# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170408_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.CardPayment'),
        ),
    ]
