# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170328_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='game',
            field=models.ManyToManyField(blank=True, null=True, to='game.Game'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CardPayment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
