# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170328_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RewardBatch',
            new_name='RewardsBatch',
        ),
    ]
