# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170327_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accumulated_spending',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
    ]
