# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170401_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='game',
            field=models.ManyToManyField(blank=True, to='game.Game'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
