# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:23
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170327_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
