# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('W', 'Windows'), ('M', 'MacOS'), ('L', 'Linux')], default='W', max_length=2),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
