# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170328_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='games'),
        ),
    ]
