# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_game_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
