# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170408_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='genres/default-img.jpg', upload_to='genres'),
            preserve_default=False,
        ),
    ]
