# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170412_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='platform_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_issue_date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
    ]
