# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170425_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
